"""Config generator -- produces config.yaml + .env from setup wizard choices.

Reads PLUGIN_META config_fields to know which values are secrets (-> .env)
and which are regular settings (-> config.yaml).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from cli.scanner import PluginInfo

logger = logging.getLogger(__name__)

# Sections of config.yaml that the setup wizard fully owns and regenerates
# from user input. Everything NOT in this list (e.g. scheduler.timezone,
# scheduler.check_interval, scheduler.default_tasks, learning.*,
# position_tracking.*, logging.*, market_data.poll_interval, and any manual
# edits the user made) must be preserved across re-runs of `clawquant setup`.
_WIZARD_OWNED_PATHS: tuple[tuple[str, ...], ...] = (
    ("ai", "providers"),
    ("ai", "default_provider"),
    ("ai", "agents"),
    ("market_data", "providers"),
    ("integrations",),
    ("risk", "rules"),
    ("scheduler", "handlers"),
)


def generate_config(
    home_dir: Path,
    enabled_plugins: list[PluginInfo],
    plugin_values: dict[str, dict[str, Any]],
    server_host: str = "127.0.0.1",
    server_port: int = 8321,
    auto_update: bool = False,
    install_commit: str = "",
    scheduler_timezone: str | None = None,
) -> tuple[Path, Path]:
    """Generate config.yaml and .env files from setup wizard results.

    Preserves any existing config.yaml fields the wizard does not manage
    (e.g. scheduler.timezone, learning.*, position_tracking.*, logging.*)
    so re-running setup does not silently reset user customizations.

    Args:
        home_dir: The ClawQuant home directory (~/.clawquant)
        enabled_plugins: List of plugins the user enabled
        plugin_values: {plugin_name: {field_key: value}} for each plugin
        server_host: HTTP server bind host
        server_port: HTTP server bind port
        auto_update: Whether startup auto-update is enabled
        install_commit: Commit hash recorded at first setup/install

    Returns:
        Tuple of (config_path, env_path)
    """
    home_dir.mkdir(parents=True, exist_ok=True)

    config_path = home_dir / "config.yaml"
    existing_config: dict[str, Any] = {}
    if config_path.exists():
        try:
            with open(config_path) as f:
                loaded = yaml.safe_load(f) or {}
            if isinstance(loaded, dict):
                existing_config = loaded
        except Exception:
            logger.warning("Could not parse existing config at %s; starting fresh", config_path)

    # Build wizard-owned sections into a fresh dict, then merge onto existing.
    wizard_config: dict[str, Any] = {}
    secrets: dict[str, str] = {}

    wizard_config["home_dir"] = str(home_dir)
    wizard_config["server"] = {"host": server_host, "port": server_port}
    wizard_config["updates"] = {
        "auto_update": bool(auto_update),
        "install_commit": str(install_commit or ""),
    }

    for plugin in enabled_plugins:
        values = plugin_values.get(plugin.name, {})
        _add_plugin_to_config(wizard_config, secrets, plugin, values)

    if scheduler_timezone:
        wizard_config.setdefault("scheduler", {})["timezone"] = scheduler_timezone

    config = _merge_with_existing(existing_config, wizard_config)

    with open(config_path, "w") as f:
        f.write("# ClawQuant Configuration\n")
        f.write("# Generated by clawquant setup\n")
        f.write("# Edit freely -- re-run 'clawquant config' to regenerate\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    # Write .env
    env_path = home_dir / ".env"
    with open(env_path, "w") as f:
        f.write("# ClawQuant Secrets\n")
        f.write("# Generated by clawquant setup\n")
        f.write("# NEVER commit this file to git\n\n")
        for key, value in sorted(secrets.items()):
            f.write(f"{key}={value}\n")

    logger.info("Config written to %s", config_path)
    logger.info("Secrets written to %s", env_path)

    return config_path, env_path


def _add_plugin_to_config(
    config: dict,
    secrets: dict,
    plugin: PluginInfo,
    values: dict[str, Any],
) -> None:
    """Add a plugin's configuration to the config dict and secrets dict."""
    category = plugin.category

    resolved_values: dict[str, Any] = {}
    for field in plugin.config_fields:
        value = values.get(field.key, field.default)
        if value is None:
            continue

        if field.type == "secret" and field.env_var:
            # Secrets go to .env, config.yaml gets ${ENV_VAR} reference
            secrets[field.env_var] = str(value)
            resolved_values[field.key] = f"${{{field.env_var}}}"
            continue

        if field.type == "number" and isinstance(value, str):
            try:
                value = float(value)
                if value == int(value):
                    value = int(value)
            except ValueError:
                pass
        resolved_values[field.key] = value

    # Build the config structure based on category
    if category == "ai_provider":
        providers = config.setdefault("ai", {}).setdefault("providers", {})
        provider_config: dict[str, Any] = {"enabled": True}
        for field in plugin.config_fields:
            val = resolved_values.get(field.key)
            if val is None:
                continue
            provider_config[field.key] = val
        providers[plugin.name] = provider_config

        # Set first provider as default if not already set
        if "default_provider" not in config.get("ai", {}):
            config.setdefault("ai", {})["default_provider"] = plugin.name

    elif category == "market_data":
        md = config.setdefault("market_data", {}).setdefault("providers", {})
        provider_config = {"enabled": True}
        for field in plugin.config_fields:
            val = resolved_values.get(field.key)
            if val is not None:
                provider_config[field.key] = val
        md[plugin.name] = provider_config

    elif category == "integration":
        integ = config.setdefault("integrations", {})
        integ_config: dict[str, Any] = {"enabled": True}
        first_channel: dict[str, Any] = {}
        for field in plugin.config_fields:
            val = resolved_values.get(field.key)
            if val is None:
                continue
            if field.key in ("chat_id", "direction"):
                first_channel[field.key] = val
            else:
                integ_config[field.key] = val

        # Preserve any extra channels the user added manually -- the wizard's
        # flat chat_id/direction fields only describe the FIRST channel.
        # `values["channels"]` carries the full list read from the existing
        # config (see setup._read_plugin_values_from_config).
        existing_channels = values.get("channels")
        channels: list[dict] = []
        if isinstance(existing_channels, list) and existing_channels:
            channels = [dict(ch) for ch in existing_channels if isinstance(ch, dict)]

        if first_channel:
            first_channel.setdefault("direction", "both")
            if channels:
                # Merge wizard's edits into the first existing channel instead
                # of replacing it, so its `id` and other metadata survive.
                channels[0] = {**channels[0], **first_channel}
            else:
                first_channel.setdefault("id", "default")
                channels.append(first_channel)

        if channels:
            integ_config["channels"] = channels
        integ[plugin.name] = integ_config

    elif category == "risk_rule":
        rules = config.setdefault("risk", {}).setdefault("rules", {})
        rule_config: dict[str, Any] = {"enabled": True}
        for field in plugin.config_fields:
            val = resolved_values.get(field.key)
            if val is not None:
                rule_config[field.key] = val
        rules[plugin.name] = rule_config

    elif category == "task_handler":
        tasks = config.setdefault("scheduler", {}).setdefault("handlers", {})
        handler_config: dict[str, Any] = {"enabled": True}
        for field in plugin.config_fields:
            val = resolved_values.get(field.key)
            if val is not None:
                handler_config[field.key] = val
        tasks[plugin.name] = handler_config

    elif category == "agent":
        agents = config.setdefault("ai", {}).setdefault("agents", {})
        agents[plugin.name] = {"enabled": True, "description": plugin.description}


def _merge_with_existing(
    existing: dict[str, Any],
    wizard: dict[str, Any],
) -> dict[str, Any]:
    """Merge wizard output onto existing config.

    - Top-level keys produced by the wizard (``home_dir``, ``server``,
      ``updates``) always win.
    - Subsections the wizard fully owns (see ``_WIZARD_OWNED_PATHS``) are
      replaced wholesale with the wizard's version so removed plugins
      actually disappear.
    - Everything else in the existing config (e.g. ``scheduler.timezone``,
      ``scheduler.check_interval``, ``scheduler.default_tasks``, ``learning``,
      ``position_tracking``, ``logging``, ``market_data.poll_interval``,
      ``market_data.history_depth``, ``ai.task_routing``, ``risk`` knobs
      outside ``rules``, and any user-added top-level keys) is preserved.
    """
    if not isinstance(existing, dict) or not existing:
        return wizard

    def _deep_merge(base: dict[str, Any], override: dict[str, Any], path: tuple[str, ...]) -> dict[str, Any]:
        out: dict[str, Any] = dict(base)
        for key, override_val in override.items():
            sub_path = path + (key,)
            if sub_path in _WIZARD_OWNED_PATHS:
                # Wizard fully owns this subtree -- replace completely.
                out[key] = override_val
                continue
            base_val = out.get(key)
            if isinstance(base_val, dict) and isinstance(override_val, dict):
                out[key] = _deep_merge(base_val, override_val, sub_path)
            else:
                out[key] = override_val
        return out

    merged = _deep_merge(existing, wizard, path=())

    # Also prune wizard-owned subtrees from the existing config if the wizard
    # didn't produce them (e.g. user disabled every market_data provider).
    # Without this, a disabled plugin could linger in config.yaml forever.
    for path in _WIZARD_OWNED_PATHS:
        _prune_if_missing(merged, wizard, path)

    return merged


def _prune_if_missing(
    merged: dict[str, Any],
    wizard: dict[str, Any],
    path: tuple[str, ...],
) -> None:
    """Remove ``merged[path]`` if ``wizard`` never populated it."""
    cursor_wizard: Any = wizard
    for part in path:
        if not isinstance(cursor_wizard, dict) or part not in cursor_wizard:
            cursor_wizard = None
            break
        cursor_wizard = cursor_wizard[part]
    if cursor_wizard is not None:
        return

    parent: Any = merged
    for part in path[:-1]:
        if not isinstance(parent, dict) or part not in parent:
            return
        parent = parent[part]
    if isinstance(parent, dict):
        parent.pop(path[-1], None)
